import torch
import torch.nn as nn


class BNInception(nn.Module):

    def __init__(self, modality):
        super(BNInception, self).__init__()
        inplace = True
        if modality == 'RGB':
            self.conv1_7x7_s2 = nn.Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3))
        if modality == 'Flow':
            self.conv1_7x7_s2 = nn.Conv2d(10, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3))
        self.conv1_7x7_s2_bn = nn.BatchNorm2d(64, eps=1e-05, momentum=0.9, affine=True)
        self.conv1_relu_7x7 = nn.ReLU(inplace)
        self.pool1_3x3_s2 = nn.MaxPool2d((3, 3), stride=(2, 2), dilation=(1, 1), ceil_mode=True)
        self.conv2_3x3_reduce = nn.Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1))
        self.conv2_3x3_reduce_bn = nn.BatchNorm2d(64, eps=1e-05, momentum=0.9, affine=True)
        self.conv2_relu_3x3_reduce = nn.ReLU(inplace)
        self.conv2_3x3 = nn.Conv2d(64, 192, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        self.conv2_3x3_bn = nn.BatchNorm2d(192, eps=1e-05, momentum=0.9, affine=True)
        self.conv2_relu_3x3 = nn.ReLU(inplace)
        self.pool2_3x3_s2 = nn.MaxPool2d((3, 3), stride=(2, 2), dilation=(1, 1), ceil_mode=True)
        self.inception_3a_1x1 = nn.Conv2d(192, 64, kernel_size=(1, 1), stride=(1, 1))
        self.inception_3a_1x1_bn = nn.BatchNorm2d(64, eps=1e-05, momentum=0.9, affine=True)
        self.inception_3a_relu_1x1 = nn.ReLU(inplace)
        self.inception_3a_3x3_reduce = nn.Conv2d(192, 64, kernel_size=(1, 1), stride=(1, 1))
        self.inception_3a_3x3_reduce_bn = nn.BatchNorm2d(64, eps=1e-05, momentum=0.9, affine=True)
        self.inception_3a_relu_3x3_reduce = nn.ReLU(inplace)
        self.inception_3a_3x3 = nn.Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        self.inception_3a_3x3_bn = nn.BatchNorm2d(64, eps=1e-05, momentum=0.9, affine=True)
        self.inception_3a_relu_3x3 = nn.ReLU(inplace)
        self.inception_3a_double_3x3_reduce = nn.Conv2d(192, 64, kernel_size=(1, 1), stride=(1, 1))
        self.inception_3a_double_3x3_reduce_bn = nn.BatchNorm2d(64, eps=1e-05, momentum=0.9, affine=True)
        self.inception_3a_relu_double_3x3_reduce = nn.ReLU(inplace)
        self.inception_3a_double_3x3_1 = nn.Conv2d(64, 96, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        self.inception_3a_double_3x3_1_bn = nn.BatchNorm2d(96, eps=1e-05, momentum=0.9, affine=True)
        self.inception_3a_relu_double_3x3_1 = nn.ReLU(inplace)
        self.inception_3a_double_3x3_2 = nn.Conv2d(96, 96, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        self.inception_3a_double_3x3_2_bn = nn.BatchNorm2d(96, eps=1e-05, momentum=0.9, affine=True)
        self.inception_3a_relu_double_3x3_2 = nn.ReLU(inplace)
        self.inception_3a_pool = nn.AvgPool2d(3, stride=1, padding=1, ceil_mode=True, count_include_pad=True)
        self.inception_3a_pool_proj = nn.Conv2d(192, 32, kernel_size=(1, 1), stride=(1, 1))
        self.inception_3a_pool_proj_bn = nn.BatchNorm2d(32, eps=1e-05, momentum=0.9, affine=True)
        self.inception_3a_relu_pool_proj = nn.ReLU(inplace)
        self.inception_3b_1x1 = nn.Conv2d(256, 64, kernel_size=(1, 1), stride=(1, 1))
        self.inception_3b_1x1_bn = nn.BatchNorm2d(64, eps=1e-05, momentum=0.9, affine=True)
        self.inception_3b_relu_1x1 = nn.ReLU(inplace)
        self.inception_3b_3x3_reduce = nn.Conv2d(256, 64, kernel_size=(1, 1), stride=(1, 1))
        self.inception_3b_3x3_reduce_bn = nn.BatchNorm2d(64, eps=1e-05, momentum=0.9, affine=True)
        self.inception_3b_relu_3x3_reduce = nn.ReLU(inplace)
        self.inception_3b_3x3 = nn.Conv2d(64, 96, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        self.inception_3b_3x3_bn = nn.BatchNorm2d(96, eps=1e-05, momentum=0.9, affine=True)
        self.inception_3b_relu_3x3 = nn.ReLU(inplace)
        self.inception_3b_double_3x3_reduce = nn.Conv2d(256, 64, kernel_size=(1, 1), stride=(1, 1))
        self.inception_3b_double_3x3_reduce_bn = nn.BatchNorm2d(64, eps=1e-05, momentum=0.9, affine=True)
        self.inception_3b_relu_double_3x3_reduce = nn.ReLU(inplace)
        self.inception_3b_double_3x3_1 = nn.Conv2d(64, 96, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        self.inception_3b_double_3x3_1_bn = nn.BatchNorm2d(96, eps=1e-05, momentum=0.9, affine=True)
        self.inception_3b_relu_double_3x3_1 = nn.ReLU(inplace)
        self.inception_3b_double_3x3_2 = nn.Conv2d(96, 96, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        self.inception_3b_double_3x3_2_bn = nn.BatchNorm2d(96, eps=1e-05, momentum=0.9, affine=True)
        self.inception_3b_relu_double_3x3_2 = nn.ReLU(inplace)
        self.inception_3b_pool = nn.AvgPool2d(3, stride=1, padding=1, ceil_mode=True, count_include_pad=True)
        self.inception_3b_pool_proj = nn.Conv2d(256, 64, kernel_size=(1, 1), stride=(1, 1))
        self.inception_3b_pool_proj_bn = nn.BatchNorm2d(64, eps=1e-05, momentum=0.9, affine=True)
        self.inception_3b_relu_pool_proj = nn.ReLU(inplace)
        self.inception_3c_3x3_reduce = nn.Conv2d(320, 128, kernel_size=(1, 1), stride=(1, 1))
        self.inception_3c_3x3_reduce_bn = nn.BatchNorm2d(128, eps=1e-05, momentum=0.9, affine=True)
        self.inception_3c_relu_3x3_reduce = nn.ReLU(inplace)
        self.inception_3c_3x3 = nn.Conv2d(128, 160, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
        self.inception_3c_3x3_bn = nn.BatchNorm2d(160, eps=1e-05, momentum=0.9, affine=True)
        self.inception_3c_relu_3x3 = nn.ReLU(inplace)
        self.inception_3c_double_3x3_reduce = nn.Conv2d(320, 64, kernel_size=(1, 1), stride=(1, 1))
        self.inception_3c_double_3x3_reduce_bn = nn.BatchNorm2d(64, eps=1e-05, momentum=0.9, affine=True)
        self.inception_3c_relu_double_3x3_reduce = nn.ReLU(inplace)
        self.inception_3c_double_3x3_1 = nn.Conv2d(64, 96, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        self.inception_3c_double_3x3_1_bn = nn.BatchNorm2d(96, eps=1e-05, momentum=0.9, affine=True)
        self.inception_3c_relu_double_3x3_1 = nn.ReLU(inplace)
        self.inception_3c_double_3x3_2 = nn.Conv2d(96, 96, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
        self.inception_3c_double_3x3_2_bn = nn.BatchNorm2d(96, eps=1e-05, momentum=0.9, affine=True)
        self.inception_3c_relu_double_3x3_2 = nn.ReLU(inplace)
        self.inception_3c_pool = nn.MaxPool2d((3, 3), stride=(2, 2), dilation=(1, 1), ceil_mode=True)
        self.inception_4a_1x1 = nn.Conv2d(576, 224, kernel_size=(1, 1), stride=(1, 1))
        self.inception_4a_1x1_bn = nn.BatchNorm2d(224, eps=1e-05, momentum=0.9, affine=True)
        self.inception_4a_relu_1x1 = nn.ReLU(inplace)
        self.inception_4a_3x3_reduce = nn.Conv2d(576, 64, kernel_size=(1, 1), stride=(1, 1))
        self.inception_4a_3x3_reduce_bn = nn.BatchNorm2d(64, eps=1e-05, momentum=0.9, affine=True)
        self.inception_4a_relu_3x3_reduce = nn.ReLU(inplace)
        self.inception_4a_3x3 = nn.Conv2d(64, 96, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        self.inception_4a_3x3_bn = nn.BatchNorm2d(96, eps=1e-05, momentum=0.9, affine=True)
        self.inception_4a_relu_3x3 = nn.ReLU(inplace)
        self.inception_4a_double_3x3_reduce = nn.Conv2d(576, 96, kernel_size=(1, 1), stride=(1, 1))
        self.inception_4a_double_3x3_reduce_bn = nn.BatchNorm2d(96, eps=1e-05, momentum=0.9, affine=True)
        self.inception_4a_relu_double_3x3_reduce = nn.ReLU(inplace)
        self.inception_4a_double_3x3_1 = nn.Conv2d(96, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        self.inception_4a_double_3x3_1_bn = nn.BatchNorm2d(128, eps=1e-05, momentum=0.9, affine=True)
        self.inception_4a_relu_double_3x3_1 = nn.ReLU(inplace)
        self.inception_4a_double_3x3_2 = nn.Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        self.inception_4a_double_3x3_2_bn = nn.BatchNorm2d(128, eps=1e-05, momentum=0.9, affine=True)
        self.inception_4a_relu_double_3x3_2 = nn.ReLU(inplace)
        self.inception_4a_pool = nn.AvgPool2d(3, stride=1, padding=1, ceil_mode=True, count_include_pad=True)
        self.inception_4a_pool_proj = nn.Conv2d(576, 128, kernel_size=(1, 1), stride=(1, 1))
        self.inception_4a_pool_proj_bn = nn.BatchNorm2d(128, eps=1e-05, momentum=0.9, affine=True)
        self.inception_4a_relu_pool_proj = nn.ReLU(inplace)
        self.inception_4b_1x1 = nn.Conv2d(576, 192, kernel_size=(1, 1), stride=(1, 1))
        self.inception_4b_1x1_bn = nn.BatchNorm2d(192, eps=1e-05, momentum=0.9, affine=True)
        self.inception_4b_relu_1x1 = nn.ReLU(inplace)
        self.inception_4b_3x3_reduce = nn.Conv2d(576, 96, kernel_size=(1, 1), stride=(1, 1))
        self.inception_4b_3x3_reduce_bn = nn.BatchNorm2d(96, eps=1e-05, momentum=0.9, affine=True)
        self.inception_4b_relu_3x3_reduce = nn.ReLU(inplace)
        self.inception_4b_3x3 = nn.Conv2d(96, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        self.inception_4b_3x3_bn = nn.BatchNorm2d(128, eps=1e-05, momentum=0.9, affine=True)
        self.inception_4b_relu_3x3 = nn.ReLU(inplace)
        self.inception_4b_double_3x3_reduce = nn.Conv2d(576, 96, kernel_size=(1, 1), stride=(1, 1))
        self.inception_4b_double_3x3_reduce_bn = nn.BatchNorm2d(96, eps=1e-05, momentum=0.9, affine=True)
        self.inception_4b_relu_double_3x3_reduce = nn.ReLU(inplace)
        self.inception_4b_double_3x3_1 = nn.Conv2d(96, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        self.inception_4b_double_3x3_1_bn = nn.BatchNorm2d(128, eps=1e-05, momentum=0.9, affine=True)
        self.inception_4b_relu_double_3x3_1 = nn.ReLU(inplace)
        self.inception_4b_double_3x3_2 = nn.Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        self.inception_4b_double_3x3_2_bn = nn.BatchNorm2d(128, eps=1e-05, momentum=0.9, affine=True)
        self.inception_4b_relu_double_3x3_2 = nn.ReLU(inplace)
        self.inception_4b_pool = nn.AvgPool2d(3, stride=1, padding=1, ceil_mode=True, count_include_pad=True)
        self.inception_4b_pool_proj = nn.Conv2d(576, 128, kernel_size=(1, 1), stride=(1, 1))
        self.inception_4b_pool_proj_bn = nn.BatchNorm2d(128, eps=1e-05, momentum=0.9, affine=True)
        self.inception_4b_relu_pool_proj = nn.ReLU(inplace)
        self.inception_4c_1x1 = nn.Conv2d(576, 160, kernel_size=(1, 1), stride=(1, 1))
        self.inception_4c_1x1_bn = nn.BatchNorm2d(160, eps=1e-05, momentum=0.9, affine=True)
        self.inception_4c_relu_1x1 = nn.ReLU(inplace)
        self.inception_4c_3x3_reduce = nn.Conv2d(576, 128, kernel_size=(1, 1), stride=(1, 1))
        self.inception_4c_3x3_reduce_bn = nn.BatchNorm2d(128, eps=1e-05, momentum=0.9, affine=True)
        self.inception_4c_relu_3x3_reduce = nn.ReLU(inplace)
        self.inception_4c_3x3 = nn.Conv2d(128, 160, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        self.inception_4c_3x3_bn = nn.BatchNorm2d(160, eps=1e-05, momentum=0.9, affine=True)
        self.inception_4c_relu_3x3 = nn.ReLU(inplace)
        self.inception_4c_double_3x3_reduce = nn.Conv2d(576, 128, kernel_size=(1, 1), stride=(1, 1))
        self.inception_4c_double_3x3_reduce_bn = nn.BatchNorm2d(128, eps=1e-05, momentum=0.9, affine=True)
        self.inception_4c_relu_double_3x3_reduce = nn.ReLU(inplace)
        self.inception_4c_double_3x3_1 = nn.Conv2d(128, 160, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        self.inception_4c_double_3x3_1_bn = nn.BatchNorm2d(160, eps=1e-05, momentum=0.9, affine=True)
        self.inception_4c_relu_double_3x3_1 = nn.ReLU(inplace)
        self.inception_4c_double_3x3_2 = nn.Conv2d(160, 160, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        self.inception_4c_double_3x3_2_bn = nn.BatchNorm2d(160, eps=1e-05, momentum=0.9, affine=True)
        self.inception_4c_relu_double_3x3_2 = nn.ReLU(inplace)
        self.inception_4c_pool = nn.AvgPool2d(3, stride=1, padding=1, ceil_mode=True, count_include_pad=True)
        self.inception_4c_pool_proj = nn.Conv2d(576, 128, kernel_size=(1, 1), stride=(1, 1))
        self.inception_4c_pool_proj_bn = nn.BatchNorm2d(128, eps=1e-05, momentum=0.9, affine=True)
        self.inception_4c_relu_pool_proj = nn.ReLU(inplace)
        self.inception_4d_1x1 = nn.Conv2d(608, 96, kernel_size=(1, 1), stride=(1, 1))
        self.inception_4d_1x1_bn = nn.BatchNorm2d(96, eps=1e-05, momentum=0.9, affine=True)
        self.inception_4d_relu_1x1 = nn.ReLU(inplace)
        self.inception_4d_3x3_reduce = nn.Conv2d(608, 128, kernel_size=(1, 1), stride=(1, 1))
        self.inception_4d_3x3_reduce_bn = nn.BatchNorm2d(128, eps=1e-05, momentum=0.9, affine=True)
        self.inception_4d_relu_3x3_reduce = nn.ReLU(inplace)
        self.inception_4d_3x3 = nn.Conv2d(128, 192, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        self.inception_4d_3x3_bn = nn.BatchNorm2d(192, eps=1e-05, momentum=0.9, affine=True)
        self.inception_4d_relu_3x3 = nn.ReLU(inplace)
        self.inception_4d_double_3x3_reduce = nn.Conv2d(608, 160, kernel_size=(1, 1), stride=(1, 1))
        self.inception_4d_double_3x3_reduce_bn = nn.BatchNorm2d(160, eps=1e-05, momentum=0.9, affine=True)
        self.inception_4d_relu_double_3x3_reduce = nn.ReLU(inplace)
        self.inception_4d_double_3x3_1 = nn.Conv2d(160, 192, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        self.inception_4d_double_3x3_1_bn = nn.BatchNorm2d(192, eps=1e-05, momentum=0.9, affine=True)
        self.inception_4d_relu_double_3x3_1 = nn.ReLU(inplace)
        self.inception_4d_double_3x3_2 = nn.Conv2d(192, 192, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        self.inception_4d_double_3x3_2_bn = nn.BatchNorm2d(192, eps=1e-05, momentum=0.9, affine=True)
        self.inception_4d_relu_double_3x3_2 = nn.ReLU(inplace)
        self.inception_4d_pool = nn.AvgPool2d(3, stride=1, padding=1, ceil_mode=True, count_include_pad=True)
        self.inception_4d_pool_proj = nn.Conv2d(608, 128, kernel_size=(1, 1), stride=(1, 1))
        self.inception_4d_pool_proj_bn = nn.BatchNorm2d(128, eps=1e-05, momentum=0.9, affine=True)
        self.inception_4d_relu_pool_proj = nn.ReLU(inplace)
        self.inception_4e_3x3_reduce = nn.Conv2d(608, 128, kernel_size=(1, 1), stride=(1, 1))
        self.inception_4e_3x3_reduce_bn = nn.BatchNorm2d(128, eps=1e-05, momentum=0.9, affine=True)
        self.inception_4e_relu_3x3_reduce = nn.ReLU(inplace)
        self.inception_4e_3x3 = nn.Conv2d(128, 192, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
        self.inception_4e_3x3_bn = nn.BatchNorm2d(192, eps=1e-05, momentum=0.9, affine=True)
        self.inception_4e_relu_3x3 = nn.ReLU(inplace)
        self.inception_4e_double_3x3_reduce = nn.Conv2d(608, 192, kernel_size=(1, 1), stride=(1, 1))
        self.inception_4e_double_3x3_reduce_bn = nn.BatchNorm2d(192, eps=1e-05, momentum=0.9, affine=True)
        self.inception_4e_relu_double_3x3_reduce = nn.ReLU(inplace)
        self.inception_4e_double_3x3_1 = nn.Conv2d(192, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        self.inception_4e_double_3x3_1_bn = nn.BatchNorm2d(256, eps=1e-05, momentum=0.9, affine=True)
        self.inception_4e_relu_double_3x3_1 = nn.ReLU(inplace)
        self.inception_4e_double_3x3_2 = nn.Conv2d(256, 256, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
        self.inception_4e_double_3x3_2_bn = nn.BatchNorm2d(256, eps=1e-05, momentum=0.9, affine=True)
        self.inception_4e_relu_double_3x3_2 = nn.ReLU(inplace)
        self.inception_4e_pool = nn.MaxPool2d((3, 3), stride=(2, 2), dilation=(1, 1), ceil_mode=True)
        self.inception_5a_1x1 = nn.Conv2d(1056, 352, kernel_size=(1, 1), stride=(1, 1))
        self.inception_5a_1x1_bn = nn.BatchNorm2d(352, eps=1e-05, momentum=0.9, affine=True)
        self.inception_5a_relu_1x1 = nn.ReLU(inplace)
        self.inception_5a_3x3_reduce = nn.Conv2d(1056, 192, kernel_size=(1, 1), stride=(1, 1))
        self.inception_5a_3x3_reduce_bn = nn.BatchNorm2d(192, eps=1e-05, momentum=0.9, affine=True)
        self.inception_5a_relu_3x3_reduce = nn.ReLU(inplace)
        self.inception_5a_3x3 = nn.Conv2d(192, 320, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        self.inception_5a_3x3_bn = nn.BatchNorm2d(320, eps=1e-05, momentum=0.9, affine=True)
        self.inception_5a_relu_3x3 = nn.ReLU(inplace)
        self.inception_5a_double_3x3_reduce = nn.Conv2d(1056, 160, kernel_size=(1, 1), stride=(1, 1))
        self.inception_5a_double_3x3_reduce_bn = nn.BatchNorm2d(160, eps=1e-05, momentum=0.9, affine=True)
        self.inception_5a_relu_double_3x3_reduce = nn.ReLU(inplace)
        self.inception_5a_double_3x3_1 = nn.Conv2d(160, 224, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        self.inception_5a_double_3x3_1_bn = nn.BatchNorm2d(224, eps=1e-05, momentum=0.9, affine=True)
        self.inception_5a_relu_double_3x3_1 = nn.ReLU(inplace)
        self.inception_5a_double_3x3_2 = nn.Conv2d(224, 224, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        self.inception_5a_double_3x3_2_bn = nn.BatchNorm2d(224, eps=1e-05, momentum=0.9, affine=True)
        self.inception_5a_relu_double_3x3_2 = nn.ReLU(inplace)
        self.inception_5a_pool = nn.AvgPool2d(3, stride=1, padding=1, ceil_mode=True, count_include_pad=True)
        self.inception_5a_pool_proj = nn.Conv2d(1056, 128, kernel_size=(1, 1), stride=(1, 1))
        self.inception_5a_pool_proj_bn = nn.BatchNorm2d(128, eps=1e-05, momentum=0.9, affine=True)
        self.inception_5a_relu_pool_proj = nn.ReLU(inplace)
        self.inception_5b_1x1 = nn.Conv2d(1024, 352, kernel_size=(1, 1), stride=(1, 1))
        self.inception_5b_1x1_bn = nn.BatchNorm2d(352, eps=1e-05, momentum=0.9, affine=True)
        self.inception_5b_relu_1x1 = nn.ReLU(inplace)
        self.inception_5b_3x3_reduce = nn.Conv2d(1024, 192, kernel_size=(1, 1), stride=(1, 1))
        self.inception_5b_3x3_reduce_bn = nn.BatchNorm2d(192, eps=1e-05, momentum=0.9, affine=True)
        self.inception_5b_relu_3x3_reduce = nn.ReLU(inplace)
        self.inception_5b_3x3 = nn.Conv2d(192, 320, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        self.inception_5b_3x3_bn = nn.BatchNorm2d(320, eps=1e-05, momentum=0.9, affine=True)
        self.inception_5b_relu_3x3 = nn.ReLU(inplace)
        self.inception_5b_double_3x3_reduce = nn.Conv2d(1024, 192, kernel_size=(1, 1), stride=(1, 1))
        self.inception_5b_double_3x3_reduce_bn = nn.BatchNorm2d(192, eps=1e-05, momentum=0.9, affine=True)
        self.inception_5b_relu_double_3x3_reduce = nn.ReLU(inplace)
        self.inception_5b_double_3x3_1 = nn.Conv2d(192, 224, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        self.inception_5b_double_3x3_1_bn = nn.BatchNorm2d(224, eps=1e-05, momentum=0.9, affine=True)
        self.inception_5b_relu_double_3x3_1 = nn.ReLU(inplace)
        self.inception_5b_double_3x3_2 = nn.Conv2d(224, 224, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        self.inception_5b_double_3x3_2_bn = nn.BatchNorm2d(224, eps=1e-05, momentum=0.9, affine=True)
        self.inception_5b_relu_double_3x3_2 = nn.ReLU(inplace)
        self.inception_5b_pool = nn.MaxPool2d((3, 3), stride=(1, 1), padding=(1, 1), dilation=(1, 1), ceil_mode=True)
        self.inception_5b_pool_proj = nn.Conv2d(1024, 128, kernel_size=(1, 1), stride=(1, 1))
        self.inception_5b_pool_proj_bn = nn.BatchNorm2d(128, eps=1e-05, momentum=0.9, affine=True)
        self.inception_5b_relu_pool_proj = nn.ReLU(inplace)
        # self.global_pool = nn.AvgPool2d (7, stride=1, padding=0, ceil_mode=True, count_include_pad=True)
        # self.last_linear = nn.Linear (1024, num_classes)

    def features(self, input):
        conv1_7x7_s2 = self.conv1_7x7_s2(input)
        conv1_7x7_s2_bn = self.conv1_7x7_s2_bn(conv1_7x7_s2)
        conv1_relu_7x7 = self.conv1_relu_7x7(conv1_7x7_s2_bn)
        pool1_3x3_s2 = self.pool1_3x3_s2(conv1_relu_7x7)
        conv2_3x3_reduce = self.conv2_3x3_reduce(pool1_3x3_s2)
        conv2_3x3_reduce_bn = self.conv2_3x3_reduce_bn(conv2_3x3_reduce)
        conv2_relu_3x3_reduce = self.conv2_relu_3x3_reduce(conv2_3x3_reduce_bn)
        conv2_3x3 = self.conv2_3x3(conv2_relu_3x3_reduce)
        conv2_3x3_bn = self.conv2_3x3_bn(conv2_3x3)
        conv2_relu_3x3 = self.conv2_relu_3x3(conv2_3x3_bn)
        pool2_3x3_s2 = self.pool2_3x3_s2(conv2_relu_3x3)
        inception_3a_1x1 = self.inception_3a_1x1(pool2_3x3_s2)
        inception_3a_1x1_bn = self.inception_3a_1x1_bn(inception_3a_1x1)
        inception_3a_relu_1x1 = self.inception_3a_relu_1x1(inception_3a_1x1_bn)
        inception_3a_3x3_reduce = self.inception_3a_3x3_reduce(pool2_3x3_s2)
        inception_3a_3x3_reduce_bn = self.inception_3a_3x3_reduce_bn(inception_3a_3x3_reduce)
        inception_3a_relu_3x3_reduce = self.inception_3a_relu_3x3_reduce(inception_3a_3x3_reduce_bn)
        inception_3a_3x3 = self.inception_3a_3x3(inception_3a_relu_3x3_reduce)
        inception_3a_3x3_bn = self.inception_3a_3x3_bn(inception_3a_3x3)
        inception_3a_relu_3x3 = self.inception_3a_relu_3x3(inception_3a_3x3_bn)
        inception_3a_double_3x3_reduce = self.inception_3a_double_3x3_reduce(pool2_3x3_s2)
        inception_3a_double_3x3_reduce_bn = self.inception_3a_double_3x3_reduce_bn(inception_3a_double_3x3_reduce)
        inception_3a_relu_double_3x3_reduce = self.inception_3a_relu_double_3x3_reduce(
            inception_3a_double_3x3_reduce_bn)
        inception_3a_double_3x3_1 = self.inception_3a_double_3x3_1(inception_3a_relu_double_3x3_reduce)
        inception_3a_double_3x3_1_bn = self.inception_3a_double_3x3_1_bn(inception_3a_double_3x3_1)
        inception_3a_relu_double_3x3_1 = self.inception_3a_relu_double_3x3_1(inception_3a_double_3x3_1_bn)
        inception_3a_double_3x3_2 = self.inception_3a_double_3x3_2(inception_3a_relu_double_3x3_1)
        inception_3a_double_3x3_2_bn = self.inception_3a_double_3x3_2_bn(inception_3a_double_3x3_2)
        inception_3a_relu_double_3x3_2 = self.inception_3a_relu_double_3x3_2(inception_3a_double_3x3_2_bn)
        inception_3a_pool = self.inception_3a_pool(pool2_3x3_s2)
        inception_3a_pool_proj = self.inception_3a_pool_proj(inception_3a_pool)
        inception_3a_pool_proj_bn = self.inception_3a_pool_proj_bn(inception_3a_pool_proj)
        inception_3a_relu_pool_proj = self.inception_3a_relu_pool_proj(inception_3a_pool_proj_bn)
        inception_3a_output = torch.cat(
            [inception_3a_relu_1x1, inception_3a_relu_3x3, inception_3a_relu_double_3x3_2, inception_3a_relu_pool_proj],
            1)

        inception_3b_1x1 = self.inception_3b_1x1(inception_3a_output)
        inception_3b_1x1_bn = self.inception_3b_1x1_bn(inception_3b_1x1)
        inception_3b_relu_1x1 = self.inception_3b_relu_1x1(inception_3b_1x1_bn)
        inception_3b_3x3_reduce = self.inception_3b_3x3_reduce(inception_3a_output)
        inception_3b_3x3_reduce_bn = self.inception_3b_3x3_reduce_bn(inception_3b_3x3_reduce)
        inception_3b_relu_3x3_reduce = self.inception_3b_relu_3x3_reduce(inception_3b_3x3_reduce_bn)
        inception_3b_3x3 = self.inception_3b_3x3(inception_3b_relu_3x3_reduce)
        inception_3b_3x3_bn = self.inception_3b_3x3_bn(inception_3b_3x3)
        inception_3b_relu_3x3 = self.inception_3b_relu_3x3(inception_3b_3x3_bn)
        inception_3b_double_3x3_reduce = self.inception_3b_double_3x3_reduce(inception_3a_output)
        inception_3b_double_3x3_reduce_bn = self.inception_3b_double_3x3_reduce_bn(inception_3b_double_3x3_reduce)
        inception_3b_relu_double_3x3_reduce = self.inception_3b_relu_double_3x3_reduce(
            inception_3b_double_3x3_reduce_bn)
        inception_3b_double_3x3_1 = self.inception_3b_double_3x3_1(inception_3b_relu_double_3x3_reduce)
        inception_3b_double_3x3_1_bn = self.inception_3b_double_3x3_1_bn(inception_3b_double_3x3_1)
        inception_3b_relu_double_3x3_1 = self.inception_3b_relu_double_3x3_1(inception_3b_double_3x3_1_bn)
        inception_3b_double_3x3_2 = self.inception_3b_double_3x3_2(inception_3b_relu_double_3x3_1)
        inception_3b_double_3x3_2_bn = self.inception_3b_double_3x3_2_bn(inception_3b_double_3x3_2)
        inception_3b_relu_double_3x3_2 = self.inception_3b_relu_double_3x3_2(inception_3b_double_3x3_2_bn)
        inception_3b_pool = self.inception_3b_pool(inception_3a_output)
        inception_3b_pool_proj = self.inception_3b_pool_proj(inception_3b_pool)
        inception_3b_pool_proj_bn = self.inception_3b_pool_proj_bn(inception_3b_pool_proj)
        inception_3b_relu_pool_proj = self.inception_3b_relu_pool_proj(inception_3b_pool_proj_bn)
        inception_3b_output = torch.cat(
            [inception_3b_relu_1x1, inception_3b_relu_3x3, inception_3b_relu_double_3x3_2, inception_3b_relu_pool_proj],
            1)

        inception_3c_3x3_reduce = self.inception_3c_3x3_reduce(inception_3b_output)
        inception_3c_3x3_reduce_bn = self.inception_3c_3x3_reduce_bn(inception_3c_3x3_reduce)
        inception_3c_relu_3x3_reduce = self.inception_3c_relu_3x3_reduce(inception_3c_3x3_reduce_bn)
        inception_3c_3x3 = self.inception_3c_3x3(inception_3c_relu_3x3_reduce)
        inception_3c_3x3_bn = self.inception_3c_3x3_bn(inception_3c_3x3)
        inception_3c_relu_3x3 = self.inception_3c_relu_3x3(inception_3c_3x3_bn)
        inception_3c_double_3x3_reduce = self.inception_3c_double_3x3_reduce(inception_3b_output)
        inception_3c_double_3x3_reduce_bn = self.inception_3c_double_3x3_reduce_bn(inception_3c_double_3x3_reduce)
        inception_3c_relu_double_3x3_reduce = self.inception_3c_relu_double_3x3_reduce(
            inception_3c_double_3x3_reduce_bn)
        inception_3c_double_3x3_1 = self.inception_3c_double_3x3_1(inception_3c_relu_double_3x3_reduce)
        inception_3c_double_3x3_1_bn = self.inception_3c_double_3x3_1_bn(inception_3c_double_3x3_1)
        inception_3c_relu_double_3x3_1 = self.inception_3c_relu_double_3x3_1(inception_3c_double_3x3_1_bn)
        inception_3c_double_3x3_2 = self.inception_3c_double_3x3_2(inception_3c_relu_double_3x3_1)
        inception_3c_double_3x3_2_bn = self.inception_3c_double_3x3_2_bn(inception_3c_double_3x3_2)
        inception_3c_relu_double_3x3_2 = self.inception_3c_relu_double_3x3_2(inception_3c_double_3x3_2_bn)
        inception_3c_pool = self.inception_3c_pool(inception_3b_output)
        inception_3c_output = torch.cat([inception_3c_relu_3x3, inception_3c_relu_double_3x3_2, inception_3c_pool], 1)

        inception_4a_1x1 = self.inception_4a_1x1(inception_3c_output)
        inception_4a_1x1_bn = self.inception_4a_1x1_bn(inception_4a_1x1)
        inception_4a_relu_1x1 = self.inception_4a_relu_1x1(inception_4a_1x1_bn)
        inception_4a_3x3_reduce = self.inception_4a_3x3_reduce(inception_3c_output)
        inception_4a_3x3_reduce_bn = self.inception_4a_3x3_reduce_bn(inception_4a_3x3_reduce)
        inception_4a_relu_3x3_reduce = self.inception_4a_relu_3x3_reduce(inception_4a_3x3_reduce_bn)
        inception_4a_3x3 = self.inception_4a_3x3(inception_4a_relu_3x3_reduce)
        inception_4a_3x3_bn = self.inception_4a_3x3_bn(inception_4a_3x3)
        inception_4a_relu_3x3 = self.inception_4a_relu_3x3(inception_4a_3x3_bn)
        inception_4a_double_3x3_reduce = self.inception_4a_double_3x3_reduce(inception_3c_output)
        inception_4a_double_3x3_reduce_bn = self.inception_4a_double_3x3_reduce_bn(inception_4a_double_3x3_reduce)
        inception_4a_relu_double_3x3_reduce = self.inception_4a_relu_double_3x3_reduce(
            inception_4a_double_3x3_reduce_bn)
        inception_4a_double_3x3_1 = self.inception_4a_double_3x3_1(inception_4a_relu_double_3x3_reduce)
        inception_4a_double_3x3_1_bn = self.inception_4a_double_3x3_1_bn(inception_4a_double_3x3_1)
        inception_4a_relu_double_3x3_1 = self.inception_4a_relu_double_3x3_1(inception_4a_double_3x3_1_bn)
        inception_4a_double_3x3_2 = self.inception_4a_double_3x3_2(inception_4a_relu_double_3x3_1)
        inception_4a_double_3x3_2_bn = self.inception_4a_double_3x3_2_bn(inception_4a_double_3x3_2)
        inception_4a_relu_double_3x3_2 = self.inception_4a_relu_double_3x3_2(inception_4a_double_3x3_2_bn)
        inception_4a_pool = self.inception_4a_pool(inception_3c_output)
        inception_4a_pool_proj = self.inception_4a_pool_proj(inception_4a_pool)
        inception_4a_pool_proj_bn = self.inception_4a_pool_proj_bn(inception_4a_pool_proj)
        inception_4a_relu_pool_proj = self.inception_4a_relu_pool_proj(inception_4a_pool_proj_bn)
        inception_4a_output = torch.cat(
            [inception_4a_relu_1x1, inception_4a_relu_3x3, inception_4a_relu_double_3x3_2, inception_4a_relu_pool_proj],
            1)

        inception_4b_1x1 = self.inception_4b_1x1(inception_4a_output)
        inception_4b_1x1_bn = self.inception_4b_1x1_bn(inception_4b_1x1)
        inception_4b_relu_1x1 = self.inception_4b_relu_1x1(inception_4b_1x1_bn)
        inception_4b_3x3_reduce = self.inception_4b_3x3_reduce(inception_4a_output)
        inception_4b_3x3_reduce_bn = self.inception_4b_3x3_reduce_bn(inception_4b_3x3_reduce)
        inception_4b_relu_3x3_reduce = self.inception_4b_relu_3x3_reduce(inception_4b_3x3_reduce_bn)
        inception_4b_3x3 = self.inception_4b_3x3(inception_4b_relu_3x3_reduce)
        inception_4b_3x3_bn = self.inception_4b_3x3_bn(inception_4b_3x3)
        inception_4b_relu_3x3 = self.inception_4b_relu_3x3(inception_4b_3x3_bn)
        inception_4b_double_3x3_reduce = self.inception_4b_double_3x3_reduce(inception_4a_output)
        inception_4b_double_3x3_reduce_bn = self.inception_4b_double_3x3_reduce_bn(inception_4b_double_3x3_reduce)
        inception_4b_relu_double_3x3_reduce = self.inception_4b_relu_double_3x3_reduce(
            inception_4b_double_3x3_reduce_bn)
        inception_4b_double_3x3_1 = self.inception_4b_double_3x3_1(inception_4b_relu_double_3x3_reduce)
        inception_4b_double_3x3_1_bn = self.inception_4b_double_3x3_1_bn(inception_4b_double_3x3_1)
        inception_4b_relu_double_3x3_1 = self.inception_4b_relu_double_3x3_1(inception_4b_double_3x3_1_bn)
        inception_4b_double_3x3_2 = self.inception_4b_double_3x3_2(inception_4b_relu_double_3x3_1)
        inception_4b_double_3x3_2_bn = self.inception_4b_double_3x3_2_bn(inception_4b_double_3x3_2)
        inception_4b_relu_double_3x3_2 = self.inception_4b_relu_double_3x3_2(inception_4b_double_3x3_2_bn)
        inception_4b_pool = self.inception_4b_pool(inception_4a_output)
        inception_4b_pool_proj = self.inception_4b_pool_proj(inception_4b_pool)
        inception_4b_pool_proj_bn = self.inception_4b_pool_proj_bn(inception_4b_pool_proj)
        inception_4b_relu_pool_proj = self.inception_4b_relu_pool_proj(inception_4b_pool_proj_bn)
        inception_4b_output = torch.cat(
            [inception_4b_relu_1x1, inception_4b_relu_3x3, inception_4b_relu_double_3x3_2, inception_4b_relu_pool_proj],
            1)

        inception_4c_1x1 = self.inception_4c_1x1(inception_4b_output)
        inception_4c_1x1_bn = self.inception_4c_1x1_bn(inception_4c_1x1)
        inception_4c_relu_1x1 = self.inception_4c_relu_1x1(inception_4c_1x1_bn)
        inception_4c_3x3_reduce = self.inception_4c_3x3_reduce(inception_4b_output)
        inception_4c_3x3_reduce_bn = self.inception_4c_3x3_reduce_bn(inception_4c_3x3_reduce)
        inception_4c_relu_3x3_reduce = self.inception_4c_relu_3x3_reduce(inception_4c_3x3_reduce_bn)
        inception_4c_3x3 = self.inception_4c_3x3(inception_4c_relu_3x3_reduce)
        inception_4c_3x3_bn = self.inception_4c_3x3_bn(inception_4c_3x3)
        inception_4c_relu_3x3 = self.inception_4c_relu_3x3(inception_4c_3x3_bn)
        inception_4c_double_3x3_reduce = self.inception_4c_double_3x3_reduce(inception_4b_output)
        inception_4c_double_3x3_reduce_bn = self.inception_4c_double_3x3_reduce_bn(inception_4c_double_3x3_reduce)
        inception_4c_relu_double_3x3_reduce = self.inception_4c_relu_double_3x3_reduce(
            inception_4c_double_3x3_reduce_bn)
        inception_4c_double_3x3_1 = self.inception_4c_double_3x3_1(inception_4c_relu_double_3x3_reduce)
        inception_4c_double_3x3_1_bn = self.inception_4c_double_3x3_1_bn(inception_4c_double_3x3_1)
        inception_4c_relu_double_3x3_1 = self.inception_4c_relu_double_3x3_1(inception_4c_double_3x3_1_bn)
        inception_4c_double_3x3_2 = self.inception_4c_double_3x3_2(inception_4c_relu_double_3x3_1)
        inception_4c_double_3x3_2_bn = self.inception_4c_double_3x3_2_bn(inception_4c_double_3x3_2)
        inception_4c_relu_double_3x3_2 = self.inception_4c_relu_double_3x3_2(inception_4c_double_3x3_2_bn)
        inception_4c_pool = self.inception_4c_pool(inception_4b_output)
        inception_4c_pool_proj = self.inception_4c_pool_proj(inception_4c_pool)
        inception_4c_pool_proj_bn = self.inception_4c_pool_proj_bn(inception_4c_pool_proj)
        inception_4c_relu_pool_proj = self.inception_4c_relu_pool_proj(inception_4c_pool_proj_bn)
        inception_4c_output = torch.cat(
            [inception_4c_relu_1x1, inception_4c_relu_3x3, inception_4c_relu_double_3x3_2, inception_4c_relu_pool_proj],
            1)

        inception_4d_1x1 = self.inception_4d_1x1(inception_4c_output)
        inception_4d_1x1_bn = self.inception_4d_1x1_bn(inception_4d_1x1)
        inception_4d_relu_1x1 = self.inception_4d_relu_1x1(inception_4d_1x1_bn)
        inception_4d_3x3_reduce = self.inception_4d_3x3_reduce(inception_4c_output)
        inception_4d_3x3_reduce_bn = self.inception_4d_3x3_reduce_bn(inception_4d_3x3_reduce)
        inception_4d_relu_3x3_reduce = self.inception_4d_relu_3x3_reduce(inception_4d_3x3_reduce_bn)
        inception_4d_3x3 = self.inception_4d_3x3(inception_4d_relu_3x3_reduce)
        inception_4d_3x3_bn = self.inception_4d_3x3_bn(inception_4d_3x3)
        inception_4d_relu_3x3 = self.inception_4d_relu_3x3(inception_4d_3x3_bn)
        inception_4d_double_3x3_reduce = self.inception_4d_double_3x3_reduce(inception_4c_output)
        inception_4d_double_3x3_reduce_bn = self.inception_4d_double_3x3_reduce_bn(inception_4d_double_3x3_reduce)
        inception_4d_relu_double_3x3_reduce = self.inception_4d_relu_double_3x3_reduce(
            inception_4d_double_3x3_reduce_bn)
        inception_4d_double_3x3_1 = self.inception_4d_double_3x3_1(inception_4d_relu_double_3x3_reduce)
        inception_4d_double_3x3_1_bn = self.inception_4d_double_3x3_1_bn(inception_4d_double_3x3_1)
        inception_4d_relu_double_3x3_1 = self.inception_4d_relu_double_3x3_1(inception_4d_double_3x3_1_bn)
        inception_4d_double_3x3_2 = self.inception_4d_double_3x3_2(inception_4d_relu_double_3x3_1)
        inception_4d_double_3x3_2_bn = self.inception_4d_double_3x3_2_bn(inception_4d_double_3x3_2)
        inception_4d_relu_double_3x3_2 = self.inception_4d_relu_double_3x3_2(inception_4d_double_3x3_2_bn)
        inception_4d_pool = self.inception_4d_pool(inception_4c_output)
        inception_4d_pool_proj = self.inception_4d_pool_proj(inception_4d_pool)
        inception_4d_pool_proj_bn = self.inception_4d_pool_proj_bn(inception_4d_pool_proj)
        inception_4d_relu_pool_proj = self.inception_4d_relu_pool_proj(inception_4d_pool_proj_bn)
        inception_4d_output = torch.cat(
            [inception_4d_relu_1x1, inception_4d_relu_3x3, inception_4d_relu_double_3x3_2, inception_4d_relu_pool_proj],
            1)

        inception_4e_3x3_reduce = self.inception_4e_3x3_reduce(inception_4d_output)
        inception_4e_3x3_reduce_bn = self.inception_4e_3x3_reduce_bn(inception_4e_3x3_reduce)
        inception_4e_relu_3x3_reduce = self.inception_4e_relu_3x3_reduce(inception_4e_3x3_reduce_bn)
        inception_4e_3x3 = self.inception_4e_3x3(inception_4e_relu_3x3_reduce)
        inception_4e_3x3_bn = self.inception_4e_3x3_bn(inception_4e_3x3)
        inception_4e_relu_3x3 = self.inception_4e_relu_3x3(inception_4e_3x3_bn)
        inception_4e_double_3x3_reduce = self.inception_4e_double_3x3_reduce(inception_4d_output)
        inception_4e_double_3x3_reduce_bn = self.inception_4e_double_3x3_reduce_bn(inception_4e_double_3x3_reduce)
        inception_4e_relu_double_3x3_reduce = self.inception_4e_relu_double_3x3_reduce(
            inception_4e_double_3x3_reduce_bn)
        inception_4e_double_3x3_1 = self.inception_4e_double_3x3_1(inception_4e_relu_double_3x3_reduce)
        inception_4e_double_3x3_1_bn = self.inception_4e_double_3x3_1_bn(inception_4e_double_3x3_1)
        inception_4e_relu_double_3x3_1 = self.inception_4e_relu_double_3x3_1(inception_4e_double_3x3_1_bn)
        inception_4e_double_3x3_2 = self.inception_4e_double_3x3_2(inception_4e_relu_double_3x3_1)
        inception_4e_double_3x3_2_bn = self.inception_4e_double_3x3_2_bn(inception_4e_double_3x3_2)
        inception_4e_relu_double_3x3_2 = self.inception_4e_relu_double_3x3_2(inception_4e_double_3x3_2_bn)
        inception_4e_pool = self.inception_4e_pool(inception_4d_output)
        inception_4e_output = torch.cat([inception_4e_relu_3x3, inception_4e_relu_double_3x3_2, inception_4e_pool], 1)

        inception_5a_1x1 = self.inception_5a_1x1(inception_4e_output)
        inception_5a_1x1_bn = self.inception_5a_1x1_bn(inception_5a_1x1)
        inception_5a_relu_1x1 = self.inception_5a_relu_1x1(inception_5a_1x1_bn)
        inception_5a_3x3_reduce = self.inception_5a_3x3_reduce(inception_4e_output)
        inception_5a_3x3_reduce_bn = self.inception_5a_3x3_reduce_bn(inception_5a_3x3_reduce)
        inception_5a_relu_3x3_reduce = self.inception_5a_relu_3x3_reduce(inception_5a_3x3_reduce_bn)
        inception_5a_3x3 = self.inception_5a_3x3(inception_5a_relu_3x3_reduce)
        inception_5a_3x3_bn = self.inception_5a_3x3_bn(inception_5a_3x3)
        inception_5a_relu_3x3 = self.inception_5a_relu_3x3(inception_5a_3x3_bn)
        inception_5a_double_3x3_reduce = self.inception_5a_double_3x3_reduce(inception_4e_output)
        inception_5a_double_3x3_reduce_bn = self.inception_5a_double_3x3_reduce_bn(inception_5a_double_3x3_reduce)
        inception_5a_relu_double_3x3_reduce = self.inception_5a_relu_double_3x3_reduce(
            inception_5a_double_3x3_reduce_bn)
        inception_5a_double_3x3_1 = self.inception_5a_double_3x3_1(inception_5a_relu_double_3x3_reduce)
        inception_5a_double_3x3_1_bn = self.inception_5a_double_3x3_1_bn(inception_5a_double_3x3_1)
        inception_5a_relu_double_3x3_1 = self.inception_5a_relu_double_3x3_1(inception_5a_double_3x3_1_bn)
        inception_5a_double_3x3_2 = self.inception_5a_double_3x3_2(inception_5a_relu_double_3x3_1)
        inception_5a_double_3x3_2_bn = self.inception_5a_double_3x3_2_bn(inception_5a_double_3x3_2)
        inception_5a_relu_double_3x3_2 = self.inception_5a_relu_double_3x3_2(inception_5a_double_3x3_2_bn)
        inception_5a_pool = self.inception_5a_pool(inception_4e_output)
        inception_5a_pool_proj = self.inception_5a_pool_proj(inception_5a_pool)
        inception_5a_pool_proj_bn = self.inception_5a_pool_proj_bn(inception_5a_pool_proj)
        inception_5a_relu_pool_proj = self.inception_5a_relu_pool_proj(inception_5a_pool_proj_bn)
        inception_5a_output = torch.cat(
            [inception_5a_relu_1x1, inception_5a_relu_3x3, inception_5a_relu_double_3x3_2, inception_5a_relu_pool_proj],
            1)

        inception_5b_1x1 = self.inception_5b_1x1(inception_5a_output)
        inception_5b_1x1_bn = self.inception_5b_1x1_bn(inception_5b_1x1)
        inception_5b_relu_1x1 = self.inception_5b_relu_1x1(inception_5b_1x1_bn)
        inception_5b_3x3_reduce = self.inception_5b_3x3_reduce(inception_5a_output)
        inception_5b_3x3_reduce_bn = self.inception_5b_3x3_reduce_bn(inception_5b_3x3_reduce)
        inception_5b_relu_3x3_reduce = self.inception_5b_relu_3x3_reduce(inception_5b_3x3_reduce_bn)
        inception_5b_3x3 = self.inception_5b_3x3(inception_5b_relu_3x3_reduce)
        inception_5b_3x3_bn = self.inception_5b_3x3_bn(inception_5b_3x3)
        inception_5b_relu_3x3 = self.inception_5b_relu_3x3(inception_5b_3x3_bn)
        inception_5b_double_3x3_reduce = self.inception_5b_double_3x3_reduce(inception_5a_output)
        inception_5b_double_3x3_reduce_bn = self.inception_5b_double_3x3_reduce_bn(inception_5b_double_3x3_reduce)
        inception_5b_relu_double_3x3_reduce = self.inception_5b_relu_double_3x3_reduce(
            inception_5b_double_3x3_reduce_bn)
        inception_5b_double_3x3_1 = self.inception_5b_double_3x3_1(inception_5b_relu_double_3x3_reduce)
        inception_5b_double_3x3_1_bn = self.inception_5b_double_3x3_1_bn(inception_5b_double_3x3_1)
        inception_5b_relu_double_3x3_1 = self.inception_5b_relu_double_3x3_1(inception_5b_double_3x3_1_bn)
        inception_5b_double_3x3_2 = self.inception_5b_double_3x3_2(inception_5b_relu_double_3x3_1)
        inception_5b_double_3x3_2_bn = self.inception_5b_double_3x3_2_bn(inception_5b_double_3x3_2)
        inception_5b_relu_double_3x3_2 = self.inception_5b_relu_double_3x3_2(inception_5b_double_3x3_2_bn)
        inception_5b_pool = self.inception_5b_pool(inception_5a_output)
        inception_5b_pool_proj = self.inception_5b_pool_proj(inception_5b_pool)
        inception_5b_pool_proj_bn = self.inception_5b_pool_proj_bn(inception_5b_pool_proj)
        inception_5b_relu_pool_proj = self.inception_5b_relu_pool_proj(inception_5b_pool_proj_bn)
        inception_5b_output = torch.cat(
            [inception_5b_relu_1x1, inception_5b_relu_3x3, inception_5b_relu_double_3x3_2, inception_5b_relu_pool_proj],
            1)
        return inception_5b_output

    def forward(self, x):
        inc5 = self.features(x)
        return inc5


def bninceptioninit(model, modality, init_path):
    own_state = model.state_dict()
    print('######initialize from TSN#####')
    if not init_path:
        if modality == 'RGB':
            init_path = 'pretrain/kinetics_rgb.pth'
        elif modality == 'Flow':
            init_path = 'pretrain/kinetics_flow.pth'
    pre_dict = torch.load(init_path, map_location=lambda storage, loc: storage)
    for k, v in pre_dict.items():
        if 'fc' in k:
            continue
        if isinstance(v, torch.nn.parameter.Parameter):
            v = v.data
        name = '.'.join((k.split('.')[-2:]))
        own_state[name].copy_(v)
    print("=> bninception loaded finetuning checkpoint ", init_path)


def bninception(modality, init_path):
    model = BNInception(modality)
    bninceptioninit(model, modality, init_path)
    return model


if __name__ == '__main__':
    model = bninception()
